CREATE TABLE  "REGISTRATION_DETAILS1" 
   (	"EMAIL" VARCHAR2(30), 
	"FIRST_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(100), 
	"CONTACT_NO" NUMBER(10,0), 
	 PRIMARY KEY ("EMAIL") ENABLE
   )
